# == In this configuration you setup AlchemyÂ´s element layouts.
#
# For further informations please see http://guides.alchemy-cms.com/create_elements.html
- name: title_with_text
  contents:
  - name: title
    type: EssenceText
  - name: text
    type: EssenceRichtext

- name: footer
  contents:
  - name: text
    type: EssenceRichtext

- name: sidebar_content
  contents:
  - name: text
    type: EssenceRichtext

- name: picture
  contents:
  - name: picture
    type: EssencePicture

- name: picture_gallery
  picture_gallery: true    